"""Add thumbnail_path to projects

Revision ID: 5da84ebfa2dd
Revises: 9824701cd145
Create Date: 2025-06-22 04:50:45.809710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da84ebfa2dd'
down_revision: Union[str, Sequence[str], None] = '9824701cd145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('thumbnail_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'thumbnail_path')
    # ### end Alembic commands ###
